notifications:
  email:
    on_success: never

dist: xenial

matrix:
  include:
    - language: python
      python:
        - "nightly"
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
    - language: node_js
      node_js:
        - "node"
      before_install:
        - sudo snap install hugo --channel=extended
      script:
        - "npm run build-prod"
